language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc

    - os: linux
      compiler: clang

    - os: osx
      compiler: clang

- stage: coverage
  script:
    - make coverage

- stage: cmake_project
  script:
  # install header only lib with cmake
  - rm -rf build || true
  - mkdir build
  - cd build
  - cmake ..
  - sudo cmake --build . --target install
  # build example project using cmake find_package
  - cd ../example
  - mkdir example_build
  - cd example_build
  - cmake ..
  - make
  - my_executable

after_success:
  # Use "-X gcov" to disable Codecov from running gcov. We already run this
  # command in "make coverage" and then delete unwanted coverage files that
  # contribute falsely to the coverage report, such as catch.hpp
  # Only send Linux (GCC) code coverage as the clang ones seem to be buggy and
  # report curly braces as unexecuted lines.
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then bash <(curl -s https://codecov.io/bash) -X gcov; fi
